### ISSUE TITLE
having problem with installing phantom js

### ISSUE THREAD

**Issue by yenumulasudhirkumar** [OlivierBlanvillain/crawler#1]
I am using blogforever crawler in ubuntu 12.04 machine. I did not understand this--- 

what does "install http://phantomjs.org/download.html to /opt/phantomjs/bin/phantomjs" means?? 

I am installing phantomjs according to the instructions given here http://phantomjs.org/build.html Is that ok? If not can some one plese explain how to install phantom js??

Thanks in Advance

**Comment by OlivierBlanvillain** [comment]
I think it meant that `/opt/phantomjs/bin/phantomjs` should be the PhantomJS executable such that if you run `/opt/phantomjs/bin/phantomjs -v` in a shell, it prints the PhantomJS version number. This path can also be changed in `bibcrawl/settings.py`.

**Comment by yenumulasudhirkumar** [comment]
@OlivierBlanvillain Thanks for the reply!! 

Your suggestion works! I have run the bash command 'which phantomjs' to know the installation path of phantomjs .I got the output '/usr/local/bin/phantomjs' and I changed the path in bibcrawl/settings.py and it is working good.

Right now I have run the crawler with an example:-

'scrapy crawl newcrawl -a startat=http://www.axomiyagaan.blogspot.in/'

All that I have managed to get is inside the img/screen folder there were screenshots downloaded and inside img/full folder i got the images downloaded.I have searched for the other extracted details like comments, titles etc.. but could'nt find any. 
- Where are the above details stored or should I have to confiure any of the details like setting path for the storage details etc.. ?
- In which format these details are stored ?

I am very much new to python and I am finding difficulty to understand the code...

So Please bear with me ..

Thanks!!

**Comment by OlivierBlanvillain** [comment]
In it's current state, the crawler does not store the blog post "details" anywhere. The last step of the extraction is defined in `pipelines/backendpropagate.py`, which you should be able to modify to save the `item: bibcrawl.model.postitem.PostItem` argument in whatever way you like.

**Comment by yenumulasudhirkumar** [comment]
Thanks for the help!
